
OVERWRITE_LOG = False
# IMMEDIATE_COMPUTE = False
CHECK_VALIDITY = False
RESOURCE_WARNINGS = False
PRINT_CG_ON_ERROR = False
LOG_LEVEL_CONSOLE = "INFO"
LOG_LEVEL_FILE = "DEBUG"
DEFAULT_MOD_PATH = "{EXP_DIR}/models/{EXP}.mod"
DEFAULT_LOG_PATH = "{EXP_DIR}/logs/{EXP}.log"
DEFAULT_REPORT_PATH = "{EXP_DIR}/reports/{EXP}"
